apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2-deployment
  labels:
    app: assignment2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assignment2-app
  template:
    metadata:
      labels:
        app: assignment2-app
    spec:
      containers:
      - name: assignment2-container
        image: 817286919980.dkr.ecr.us-east-1.amazonaws.com/dlamb9/assignment2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: assignment2-service
spec:
  type: LoadBalancer
  selector:
    app: assignment2-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
# ---
## doesn't work in aws!
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: assignment2-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: assignment2-service
#           servicePort: 80
