apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2-workload
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-assignment2-workload
  template:
    spec:
      containers:
      - image: assignment2
        imagePullPolicy: Always
        name: assignment2-workload
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
